services:
  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d testdb -U testuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://testuser:testpassword@db:5432/testdb?sslmode=disable
    volumes:
      - ./migrations:/migrations
    command: -path /migrations -database postgres://testuser:testpassword@db:5432/testdb?sslmode=disable up
