services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mydb -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb?sslmode=disable
    volumes:
      - ./migrations:/migrations
    command: -path /migrations -database postgres://myuser:mypassword@db:5432/mydb?sslmode=disable up
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
volumes:
  pgdata:
